---
platform: darwin

params:
  - PATH: /Users/caporasolab/miniconda3/bin:/usr/bin:/bin:/usr/sbin:/sbin
  - LC_ALL: en_US.UTF-8
  - LANG: en_US.UTF-8

inputs:
  - name: busywork
  - name: q2-feature-table-channel
  - name: qiime2-channel
  - name: q2templates-channel
  - name: q2-types-channel

run:
  path: busywork/ci/master/tasks/q2-feature-table/test.sh
