---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: continuumio/miniconda3
    version: latest

inputs:
  - name: busywork
  - name: q2-feature-table-channel
  - name: qiime2-channel
  - name: q2templates-channel
  - name: q2-types-channel

run:
  path: busywork/ci/master/tasks/q2-feature-table/test.sh
