---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: continuumio/miniconda3
    version: latest

inputs:
  - name: build-linux
  - name: build-darwin

outputs:
  - name: builds

run:
  path: busywork/ci/master/tasks/merge.sh
