---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: continuumio/miniconda3
    version: latest

inputs:
  - name: busywork
  - name: builds
  - name: qiime2-channel

run:
  path: busywork/ci/master/tasks/test-q2cli.sh
