---

- name: make ftp dir
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - "{{ ftp_dir }}"
    - "{{ ftp_dir }}/pass"
    - "{{ ftp_dir }}/data"

- name: copy passdb
  copy:
    src: "{{ passdb }}"
    dest: "{{ ftp_dir }}/pass"

- name: copy ftp server docker compose template
  template:
    src: "{{ item }}"
    dest: "{{ ftp_dir }}"
  with_items:
    - ftp_server.yml
    - Dockerfile

- name: start ftp containers
  become: True
  command: /usr/local/bin/docker-compose -f {{ ftp_dir }}/ftp_server.yml up --build -d
  register: dc
  changed_when: '"Creating ftp_server_1" in dc.stderr'
