---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: condaforge/linux-anvil
    version: latest

params:
  - PATH: /opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin

inputs:
  - name: busywork
  - name: q2-types-source
  - name: qiime2-channel

outputs:
  - name: build-linux

run:
  path: busywork/ci/master/tasks/q2-types/build.sh
