db:
  image: postgres:9.5
  volumes:
    - {{ base_dir }}/{{ pgdata_dir }}:/var/lib/postgresql/data
  environment:
    POSTGRES_DB: {{ pg_db }}
    POSTGRES_USER: {{ pg_user }}
    POSTGRES_PASSWORD: {{ pg_pass }}

web:
  image: concourse/concourse
  links:
    - db
  command: web
  ports:
    - 127.0.0.1:{{ service_port }}:8080
    # Docker mangles iptables --- eventually we should adjust this in
    # coordination with UFW
    - 2345:2222
  volumes:
    - {{ base_dir }}/{{ keys_dir }}:/concourse-keys
  environment:
    CONCOURSE_PUBLICLY_VIEWABLE: 'true'
    CONCOURSE_BASIC_AUTH_USERNAME: {{ auth_user }}
    CONCOURSE_BASIC_AUTH_PASSWORD: {{ auth_pass }}
    CONCOURSE_EXTERNAL_URL: {{ protocol }}://{{ external_host }}:{{ public_port }}
    CONCOURSE_POSTGRES_DATA_SOURCE: postgres://{{ pg_user }}:{{ pg_pass }}@db:5432/{{ pg_db }}?sslmode=disable
